export const quoteLibrary = [
  {
    category: 'life',
    index: 0,
    quotes: [
      `Essentialism: only once you give yourself permission to stop trying to do it all, to stop saying yes to everyone, can you make your highest contribution towards the things that really matter. - Greg McKeown`,
      `The way of the Essentialist is the relentless pursuit of less but better - Greg McKeown`,
      `The way of the Essentialist means living by design, not by default. - Greg McKeown`,
      `We often think of choice as a thing. But a choice is not a thing. Our options may be things, but a choice—a choice is an action. It is not just something we have but something we do - Greg McKeown`,
      `Instead of asking, "What do I have to give up?" they ask, "What do I want to go big on?" The cumulative impact of this small change in thinking can be profound. - Greg McKeown`,
      `The best asset we have for making a contribution to the world is ourselves. If we underinvest in ourselves, and by that I mean our minds, our bodies, and our spirits, we damage the very tool we need to make our highest contribution. - Greg McKeown`,
      `An essential intent is both inspirational and concrete, both meaningful and measurable - Greg McKeown`,
      `Instead of asking, "How much do I value this item?" we should ask, "If I did not own this item, how much would I pay to obtain it?" - Tom Stafford`,
      `Don’t ask, "How will I feel if I miss out on this opportunity?" but rather, "If I did not have this opportunity, how much would I be willing to sacrifice in order to obtain it?" - Greg McKeown`,
      `The life of an Essentialist is a life lived without regret. If you have correctly identified what really matters, if you invest your time and energy in it, then it is difficult to regret the choices you make. You become proud of the life you have chosen to live. - Greg McKeown`,
      `There is no substitute for learning from experience. - Timothy Gallwey`,
      `The difference between winning and losing is most often not quitting. - Walt Disney`,
      `Above all, it’s the quality of your relationships that will determine the quality of your life. - Esther Perel`,
      `learn from defeats when they happen. In fact, if you are not encountering defeat on a fairly regular basis, you are not trying hard enough. And absolutely refuse to accept less than your best. - Coach Sommer`,
      `Don't feel behind. Compare yourself to yourself yesterday, not to younger people who aren't you. - David Epstein`,
      `Focus on what’s in front of you, design great days to create a great life, and try not to make the same mistake twice. That’s it - Tim Ferriss`,
      `Start now. Optimize later. An imperfect start can always be improved, but obsessing over a perfect plan will never take you anywhere on its own. - James Clear`,
      `Difficult conversations threaten our 3 core identities. Am I competent? Am I a good person? Am I worthy of love? - Douglas Stone`,
      `All-or-nothing identities are about as sturdy as a two-legged stool. - Douglas Stone`,
      `Don’t mistake a goal-supportive action for the goal itself. You aren’t off the hook just because you did one thing consistent with your goal. - Kelly McGonigal`,
      `The what-the-hell effect is an attempt to escape the bad feelings that follow a setback. Without the guilt and self-criticism from self-compassion, there’s nothing to escape. - Kelly McGonigal`,
      `Surf the urge: imagine a urge/craving as a wave in the ocean. Ride the wave. Don't fight it but don't give in. The wave will ultimately crash and dissolve. - Kelly McGonigal`,
      `Be forgiving with your past self. Be strict with your present self. Be flexible with your future self. - James Clear`,
      `Failure is just another name for much of real life. - Margaret Atwood`,
      `Broken hearts, like broken legs, need a lot of tending to in order to properly heal. Unless you don’t mind the possibility of your heart’s healing  a little bit closed, a whole lot defensive, and way too easily bruised moving forward from here. - Katherine Thomas`,
      `Learn how to make amends to yourself in a way that frees you from the residue of resentment and regret. - Katherine Thomas`,
      `Kindness is contagious. It’s hard for someone to stay mean and petty when you’re behaving in ways that are consistently thoughtful, respectful, and generous. - Katherine Thomas`,
      `If you don’t like being a doormat, then get off the floor. - Al Anon`,
      `Cry. Forgive. Learn. Move on. Let your tears water the seeds of your future happiness. - Steve Maraboli`,
      `Getting over a painful experience is much like crossing monkey bars. You have to let go at some point in order to move forward. -  C.S. Lewis `,
      `The only people you should get even with are those who have helped you. - John E. Southard`,
      `Where you spend your attention is where you spend your life. - James Clear`,
      `Ideal images of perfection, if they are used for inspiration, they can be very beneficial; but if they are used as a measuring device, they become our downfall. - Thomas Sterner`,
      `Introversion is a preference for environments that are not overstimulating. - Susan Cain`,
      `Dare to be truthful. - Jordan Peterson`,
      `Consult your resentment. It always means one of two things. Either the resentful person is immature, in which case he or she should shut up and get on with it. Or is being/ allowing yourself to be taken advantage of. - Jordan Peterson`,
      `When confronted with new evidence, it is a very different narrative to say, “I was 58% but now I’m 46%.” instead of “I thought I was right but now I’m wrong.” - Annie Duke`,
      `Identify the things in your life that make you happy and do more of them. Identify the things in your life that make you unhappy and do less of them. - John Boyd`,
      `Life is not like chess. Chess contains no hidden information and very little luck. Life is more like poker. You could make the smartest, most careful decision and still have it blow up in your face. - Annie Duke`,
      `We can buy food, objects, space (i.e. land), but not time. Once we lose time, we lose it forever. - John Boyd`,
      `How you spend today ultimately determines both your past and future. - John Boyd`,
      `Future-oriented people tend to be more successful professionally and academically, to eat well, to exercise regularly, and to schedule preventative doctor's exams. But they are the least likely to help others in need. - John Boyd`,
      `Each day you make hundreds of decisions: What to wear, what to eat... whom to avoid. On any given day, these decisions appear trivial, even inconsequential. Taken as a whole, they define who you were, who you are, and who you will become. - John Boyd`,
      `Nothing creates more stress than when our actions and behaviors are not congruent with our values. - Darren Hardy`,
      `When you define your goals, you give your brain something new to look for and focus on. - Darren Hardy`,
      `I'm constantly weeding out of my life people who refuse to grow and live positively. - Darren Hardy`,
      `Never ask advice of someone with whom you wouldn't want to trade places. - Darren Hardy`,
      `You get in life what you tolerate. If you tolerate your body being overweight, tired, and perpetually sick, it will be. - Darren Hardy`,
      `Everything is a chance to do and be your best. - Ryan Holiday`,
      `Fear doesn't go away. The battle must be fought anew every day. - Steven Pressfield`,
      `The problem with friends and family is that they know us as we are. They are invested in maintaining us as we are. The last thing we want is to remain as we are. - Steven Pressfield`,
      `Resentment, bitterness, and holding a grudge prevent us from seeing and hearing and tasting and delighting. - Pema Chodron`,
      `Deprive yourself of the usual cognitive crutch of pretending that tomorrow will be different. - Kelly McGonigal`,
      `Each day is a new battle to say yes to what matters and say no to what doesn't. Focus is a practice. - James Clear`,
      `Life is not always a matter of holding good cards, but sometimes, playing a poor hand well. - Jack London`,
      `Your actions are a consequence of your thoughts. Your thoughts are a consequence of what you consume. - James Clear`,
      `Almost everything will work again if you unplug it for a few minutes, including you. - James Clear`,
      `Life is too short to not be pursuing the best opportunity you know of. - James Clear`,
      `Your identity can hold you back …or build you up. Build habits that reinforce your desired identity. - James Clear`,
      `Whatever you are not changing, you are choosing. - Laurie Buchanan`,
      `A habit is a lifestyle to be lived, not a finish line to be crossed. Make small, sustainable changes you can stick with. - James Clear`,
      `Most failures are one-time costs. Most regrets are recurring costs. The pain of inaction stings longer than the pain of incorrect action. - James Clear`,
      `There are three things you cannot buy. Fitness: You have to keep fit, whether you're rich or not. Diet: You cannot pay someone to be on a diet for you.…Then, looking after your soul. No one can possibly treat your soul but you yourself. - Brunello Cucinelli`,
      `You can't guarantee success, but you can guarantee failure: never try. - James Clear`,
      `You know yourself mostly by your thoughts. Everyone else in the world knows you only by your actions. Remember this when you feel misunderstood. You have to do or say something for others to know how you feel. - James clear`,
      `Life is not a dress rehearsal—this is probably it. Make it count. - Sam Altman`,
      `If you do it right failure becomes growth. - Tommy Caldwell`,
      `Remember frustration is a function of our expectations and our expectations are often a reflection of the social mirror rather than our own values and priorities. - Stephen R. Covey`,
      `One of the most important ways to manifest integrity is to be loyal to those who are not present. - Stephen R. Covey`,
      `Seek first to understand then to be understood. - Stephen R. Covey`,
      `The NR (New Rich) aims to distribute mini retirements throughout life instead of hoarding the recovery and enjoyment for the fool's gold of retirement. - Timothy Ferriss`,
      `Fear setting: Define your nightmare the absolute worst that could happen if you did what you are considering. - Timothy Ferriss`,
      `As I have heard said a person's success in life can usually be measured by the number of uncomfortable conversations, he or she is willing to have. - Timothy Ferriss`,
      `Excitement is the more practical synonym for happiness and it is precisely what you should strive to chase. It is the cure-all. - Timothy Ferriss`,
      `You are the average of the five people you associate with most so do not underestimate the effects of your pessimistic unambitious or disorganized friends. If someone isn't making you stronger, they're making you weaker. - Timothy Ferriss`,
      `The key to having a good life is to value things that are genuinely valuable and be indifferent to things that lack value. - William Irvine`,
      `You are not controlled by the past. - Ichiro Kishimi`,
      `Personality is something that you choose for yourself. External factors had a significant influence on that choice. But you chose this kind of self. - Ichiro Kishimi`,
      `No matter what has occurred in your life up to this point it has no bearing at all on how you live from now on. - Ichiro Kishimi`,
      `Loneliness is having other people around you and having a deep sense of being excluded from them. To feel lonely, we need other people. - Ichiro Kishimi`,
      `Don't become so annoyed by someone that you become a source of annoyance to others. - Derren Brown`,
      `Plan for success. Prepare for failure. - Derren Brown`,
      `Life is chess. Your plan is affected by the inclinations of the other player. You must modify your plan constantly. - Derren Brown`,
      `If your walls are severely cracked no amount of wallpaper will solve the problem. - Derren Brown`,
      `Memory brings back the agony of fear while foresight brings it on prematurely. - Derren Brown`,
      `You'll never regret falling in love. Do so over and over again. - Derren Brown`,
      `Focus our awareness and energy on those things and people that bring us pleasure. - Gordon Livingston`,
      `Enjoy life even as we are surrounded by evidence of its brevity and potential for disaster. - Gordon Livingston`,
      `Forgiveness is not something we do for others; it is a gift to ourselves. - Gordon Livingston`,
      `I'm constantly weeding out of my life people who refuse to grow and live positively. - Darren Hardy`,
      `You must keep the promises you make to yourself and reward yourself so that you can trust and motivate yourself. - Jordan Peterson`,
      `Happiness is found in the journey uphill and not in the fleeting sense of satisfaction awaiting at the next peak. - Jordan Peterson`,
      `You must determine where you have been in your life so that you can know where you are now. `,
      `You can't quit on a bad day. - Angela Duckworth`,
      `You always hold the rights to your effort, but never to your results.Results are entitled to no one. At best, they are on loan and must be renewed each day.All you own is the right to try. - James Clear`,
      `Reading is the nourishment that lets you do interesting work. - Jennifer Egan`,
      `The Paradox of Freedom:The way to expand your freedom is to narrow your focus. Stay focused on training to achieve physical freedom. Stay focused on learning to achieve intellectual freedom. - James Clear`,
      `Why would I think about missing a shot that I haven’t taken yet? - Michael Jordan`,
      `When people say they don’t want to change what they really mean is they don’t have an incentive to change.Change the incentives and the behavior follows suit. - James Clear`,
      `Not everything that is faced can be changed, but nothing can be changed until it is faced. - James Baldwin`,
      `Don’t be someone who mistook motion for meaning. Everyone thought I was thriving but, on the inside, I was dying. - Jerry Colona`,
      `Radical self-inquiry. Radical in that it demands that we stop blaming others for our lives.  - Jerry Colona`,
      `Slow down. Stand still. Breathe. Let the forest find you. - Jerry Colona`,
      `The call is to authenticity. The call is to be real; to show up mad, scared, fearless, or joyful—or all the above. - Jerry Colona`,
      `If you allow it, each footstep can be a do-over.  - Jerry Colona`,
      `Much of what we do is driven by fear of failure. - Gordon Livingston `,
      ` If I allow myself, I can have an infinite number of do-overs. - Jerry Colona`,
      `True grit is kind. True grit is persistent. - Jerry Colona`,
      `Do you see it? my therapist asks. Do you see that the more you plot, the cleverer you feel? And the cleverer you feel, the more hooked on the anger you become? You nurse and feed that anger until you're operating purely out of your shadow. - Jerry Colona`,
      `Numb feel: It is possible - at least for some of the people some of the time - to be happy, sad, bored, or curious, and not know it. - Daniel Gilbert`,
      `It doesn't take much to convince us that we are smart and healthy, but it takes a lot of facts to convince us of the opposite. - Daniel Gilbert`,
      `Infrequent or unusual experiences are the most memorable. - Daniel Gilbert`,
      `The statute of limitations has expired on most of our childhood traumas. - Unknown`,
      `Your mind isn't magic. It's a moist computer you can program. - Scott Adams`,
      `Many people think they lack motivation when what they really lack is clarity. - James Clear`,
      `Show up. Listen. Try to laugh. - Anna Quindlen`,
      `When trying something new, do it on a scale where failure is survivable. - Tim Harford`,
      `The hardest thing of all is to learn to love the journey, not the destination. - Anna Quindlen`,
      `Our response to failure should be, “I am not a failure, but I have made a mistake.” - Tim Harford`,
      `If you desire to do great things, then remember that you must give things your full attention — not just a mild effort — and leave many other things alone for the time being. - Epictetus`,
      `Each day, keep in mind that death can be close to you. You will not take your time for granted. - Epictetus`,
      `It is not that we have a short time to live, but that we waste a lot of it. Life is long enough, and a sufficiently generous amount has been given to us for the highest achievements if it were all well invested. - Seneca`,
      `We are not given a short life, but we make it short, and we are not ill-supplied but wasteful of it.  - Seneca`,
      `Life is long if you know how to use it. - Seneca`,
      `You are living as if destined to live for ever, though all the while that very day which you are devoting to somebody or something may be your last. - Seneca`,
      `Living is the least important activity of the preoccupied man; yet there is nothing which is harder to learn. - Seneca`,
      `But putting things off is the biggest waste of life: it snatches away each day as it comes and denies us the present by promising the future. - Seneca`,
      `The whole future lies in uncertainty: live immediately. - Seneca`,
      `Life is very short and anxious for those who forget the past, neglect the present, and fear the future. - Seneca`,
      `Meditation is like doing focused reps for your mind. Focus on the breath, lose your focus, bring it back to the breath, repeat. This is the whole game. Keep bringing your mind back to the breath. -  Dan Harris`,
      `Envy is fuelled by a sense of entitlement and a perpetual comparing of ourselves to our peers. - Derren Brown`,
      `We commonly spend our lives focused on the future: this carrot dangles before us. It is easy to follow the carrot and harder to think about what might truly make us happy. The carrot might not even be edible. - Derren Brown`,
      `We can take responsibility for how we feel by realising that ultimately it is our after-the-event, ongoing reactions to what happens around us that are the cause of our problems. - Derren Brown`,
      `If something concerns anything not in our control, be prepared to say that it is nothing to you. - Derren Brown`,
      `When we try to control something over which we have no authority, we will of course fail, and we set ourselves up for frustration and anxiety along the way. - Derren Brown`,
      `Criticisms make us defensive or upset, and flattery sinks in too deeply. - Derren Brown`,
      `we are terrible at reading each other's thoughts. Yet we consistently behave as if we have been endowed with this entirely handsome ability. - Derren Brown`,
      `We can't blame others for doing what we would most likely have done if we found ourselves in the same circumstances. - Derren Brown`,
      `Guilt is attached to the past in the same way that fear is attached to the future. - Derren Brown`,
      `Whatever the past is, it has been and gone. If there are things you need to face in your past because they refuse to let you go, realise at least that they grip you not because they control you (they no longer exist), but because of the narrative they've left you with. - Derren Brown`,
      `Whose expectations am I trying to fulfill? My own or those of someone else? - James Clear`,
      `Will this matter in six months? - James Clear`,
      `Am I tolerating my flaws or improving them? - James Clear`,
      `In what ways are you a difficult person to work with? What can you learn from that? - James clear`,
      `Over the last 10 years, what has become more important to you? What has become less important? - James Clear`,
      `What do you really wish you had the courage to do? - James Clear`,
      `Am I climbing the right mountain? - James Clear`,
      `What are you avoiding just because you know the answer is painful? - James Clear`,
      `What is the most neglected important area in my life right now? - James Clear`,
      `Am I happy with the trade offs I am making in my life right now? - James Clear`,
      `How would the person I wish to be act today? - James Clear`,
      `How are you contributing to your own struggle? - James Clear`,
      `Can my current habits carry me to my desired future? - James Clear`,
      `Our response to failure should be, “I am not a failure, but I have made a mistake.” - Tim Harford`,
    ],
  },
  {
    category: 'habit',
    index: 1,
    quotes: [
      `What looks like a talent gap is often a focus gap.The 'all star' is often an average to above average performer who spends more time working on what is important and less time on distractions.The talent is staying focused.`,
      `Minimal viable progress. We can ask ourselves, "What is the smallest amount of progress that will be useful and valuable to the essential task we are trying to get done?" - Greg McKeown`,
      `Procrastinating on something important is choosing to delay a better future.`,
      `Resistance Only Opposes in One Direction. Resistance obstructs movement only from a lower sphere to a higher. - Steven Pressfield`,
      `Resistance Is Most Powerful At The Finish Line. The danger is greatest when the finish line is in sight. - Steven Pressfield`,
      `Procrastination is the most common manifestation of Resistance because it’s the easiest to rationalize - Steven Pressfield`,
      `The most pernicious aspect of procrastination is that it can become a habit. We don’t just put off our lives today; we put them off till our deathbed - Steven Pressfield`,
      `If you find yourself criticizing other people, you’re probably doing it out of Resistance. When we see others beginning to live their authentic selves, it drives us crazy if we have not lived out our own - Steven Pressfield`,
      `Rationalization is Resistance’s right-hand man. Its job is to keep us from feeling the shame we would feel if we truly faced what cowards we are for not doing our work. - Steven Pressfield`,
      `"I write only when inspiration strikes," he replied. "Fortunately it strikes every morning at nine o’clock sharp." - Somerset Maugham`,
      `Resistance gets us to plunge into a project with an overambitious and unrealistic timetable for its completion. It knows we can’t sustain that level of intensity. We will hit the wall. We will crash - Steven Pressfield`,
      `The professional dedicates himself to mastering technique not because he believes technique is a substitute for inspiration but because he wants to be in possession of the full arsenal of skills when inspiration does come. - Steven Pressfield`,
      `You’re not responsible for the hand of cards you were dealt. You’re responsible for maxing out what you were given. - Chris Sommer`,
      `We are what we repeatedly do, therefore, excellence is not an act, but a habit - Aristotle`,
      `Yet rather than avoiding this inevitable tedium, you must accept and embrace it. The pain and boredom we experience in the initial stage of learning a skill toughens our minds, much like physical exercise. - Robert Greene`,
      `It is better to dedicate two or three hours of intense focus to a skill than to spend eight hours of diffused concentration on it. - Robert Greene`,
      `In the vast majority of the professions and vocations, the people who succeed are not any cleverer than you. - Matt Ridley`,
      `For most people brought up in this society, the plateau can be a form of purgatory. It triggers disowned emotions. It flushes out hidden motivations. - George Leonard`,
      `It’s fine to have ambitious goals, but the best way of reaching them is to cultivate modest expectations at every step along the way. When you’re climbing a mountain don’t keep looking up at the peak. Keep your eyes on the path. - George Leonard`,
      `Blame is the creed of the disempowered. - Steve Maraboli`,
      `It's easy to get on the path of mastery. The real challenge lies in staying on it. - George Leonard`,
      `Surrender to your teacher and to the demands of your discipline. Surrender your proficiency to reach a higher level of proficiency. - George Leonard`,
      `Practice is best conceived of as a noun, not as something you do, but as something you have, something you are. - George Leonard`,
      `The hacker is willing to stay on the plateau indefinitely. - George Leonard`,
      `The Obsessive finds themselves on a plateau and won't accept it. He doesn't understand the necessity for periods of development on the plateau - George Leonard`,
      `The Dabbler loves the newness. Thinks they are a connoisseur of novelty but really just an eternal kid. Dabbler/Obsessive/Hacker - George Leonard`,
      `Practice for the sake of practice itself. Love the plateau. - George Leonard`,
      `Mastery is available to anyone willing to get on the path and stay on it. - George Leonard`,
      `Before quitting, ask yourself what measurable progress you’re making. You’re either moving forward, falling behind, or standing still. - Seth Godin`,
      `When do you feel smart: when you’re flawless or when you’re learning? - Carol Dweck`,
      `Habits are the closest we can get to having superpowers. - Tynan`,
      `How many of us have become drunks and drug addicts, succumbed to painkillers, gossip, and compulsive cell-phone use, simply because we don’t do that thing that our hearts, our inner genius, is calling us to? Resistance defeats us. - Steven Pressfield`,
      `A victim act is a form of passive aggression. It seeks to achieve gratification not by honest work or a contribution made out of one’s experience or insight or love, but by the manipulation of others through silent (and not-so-silent) threat. - Steven Pressfield`,
      `Resistance seems to come from outside ourselves. We locate it in spouses, jobs, bosses, kids. Resistance arises from within. It is self-generated and self-perpetuated. - Steven Pressfield`,
      `What better way of avoiding work than going to a workshop? - Steven Pressfield`,
      `The Marine Corps teaches you how to be miserable. This is invaluable for an artist. - Steven Pressfield`,
      `Avoid survivorship bias. Don't just see success. See all the failures that led to the eventual success. - Tim Harford`,
      `Do you really need to think more, or is it simply a matter of doing the work? - James Clear`,
      `Top people have very clear goals. They know who they are, and they know what they want. They write it down and they make plans for its accomplishment. Unsuccessful people carry their goals around in their head like marbles rattling around in a can. - Darren Hardy`,
      `Once you get momentum, you will be hard to stop—virtually unbeatable.  - Darren Hardy`,
      `Knowledge does not change behavior. We have all encountered crazy shrinks and obese doctors and divorced marriage counselors. - Chip Heath`,
      `Change is easier when you know where you're going and why it's worth it. - Chip Heath`,
      `Don't think. Act. We can always revise and revisit once we've acted. But we can accomplish nothing until we act. - Steven Pressfield`,
      `When is the best time to start? Start Before You're Ready. Don’t prepare. Begin. - Steven Pressfield`,
      `The enemy is our chattering brain, which, if we give it so much as a nanosecond, will start producing excuses, alibis, transparent self-justifications. - Steven Pressfield`,
      `Better to have written a lousy ballet than to have composed no ballet at all. - Steven Pressfield`,
      `The longer we cleave to this shadow life, the farther we drift from our true purpose, and the harder it becomes for us to rally the courage to get back. - Steven Pressfield`,
      `To follow a calling requires work. It's hard. It hurts. It demands entering the pain-zone of effort, risk, and exposure. - Steven Pressfield`,
      `Addictions embody repetition without progress. They produce incapacity as a payoff. - Steven Pressfield`,
      `The amateur is terrified that if the tribe should discover who he really is, he will be kicked out into the cold to die. - Steven Pressfield`,
      `The tribe doesn't give a shit. There is no tribe. Just a conglomeration of individuals who are just as fucked up as we are and just as terrified. Each individual is so caught up in his own bullshit that he doesn't have two seconds to worry about yours. - Steven Pressfield`,
      `The sure sign of an amateur is he has a million plans and they all start tomorrow. - Steven Pressfield`,
      `Turning pro is like kicking a drug habit or stopping drinking. It's a decision, a decision to which we must re-commit every day - Steven Pressfield`,
      `No excuses. If you aren't good at something, work harder, work smarter. - Darren Hardy`,
      `If you have good habits, time becomes your ally. All you need is patience. - James Clear`,
      `Knowledge is the compound interest of curiosity. - James Clear`,
      `The Cycle of Improvement: Awareness, deliberate practice, habit, repeat - James Clear`,
      `If you want to look good in front of thousands, you have to outwork thousands in front of nobody. - Damian Lillard`,
      `There are 3 primary drivers of results in life:1) Your luck (randomness).2) Your strategy (choices).3) Your actions (habits).Only 2 of the 3 are under your control. But if you master those 2, you can improve the odds that luck will work for you rather than against you. - James Clear`,
      `Self-control is highest in the morning and steadily deteriorates over the course of the day. - Kelly McGonigal`,
      `Stress is the enemy of willpower. So often we believe that stress is the only way to get things done, and we even look for ways to increase stress. - Kelly McGonigal`,
      `People who are distracted are more likely to give in to temptations. - Kelly McGonigal`,
      `Unnecessary activity is a way of keeping ourselves busy so we don't have to feel any pain. - Pema Chodron`,
      `The best way to improve your self-control is to see how and why you lose control. - Kelly McGonigal`,
      `Imagine that this challenge will get easier for you over time if you are willing to do what is difficult now. - Kelly McGonigal`,
      `Whenever there is a gap between your habits and your goals, your habits will always win. - James Clear`,
      `Habits will form whether you want them or not. Whatever you repeat, you reinforce. - James Clear`,
      `Start now. Optimize later. An imperfect start can always be improved, but obsessing over a perfect plan will never take you anywhere on its own - James Clear`,
      `You may have a fresh start any moment you choose, for this thing that we call failure is not the falling down, but the staying down. - Mary Pickford`,
      `The most dangerous items on your to-do list are the ones that look like opportunities but are actually distractions. - James Clear`,
      `Optimize for tomorrow—as in, literally, one day from now. Save to be a little richer tomorrow. Exercise to be a little fitter tomorrow. Read to be a little smarter tomorrow. - James Clear`,
      `A year from now you will wish you had started today. - Karen Lamb`,
      `Before you dream about the view from the summit, ask yourself if you're willing to keep your head down, focus on the path, and spend your life walking up the side of a very big hill. It takes years of walking to earn a minute at the top - James Clear`,
      `Your actions are your real priorities. - James Clear`,
      `Rome wasn't built in a day, but they were laying bricks every hour. - James Clear`,
      `Mental endurance is a measure of the ability to sustain focus and concentration over time. - Jim Loehr`,
      `Be brutally honest about what you know and don't know. Then see what's missing, identify the gaps, and fill them in. - Michael Starbird`,
      `Make mistakes: Fail to succeed. Intentionally get it wrong to inevitably get it even more right. - Michael Starbird`,
      `If you can't explain it, you don't know it. - Michael Starbird`,
      `If you are insecure guess what? The rest of the world is too. Do not overestimate the competition and underestimate yourself. You are better than you think. - Timothy Ferriss`,
      `At least three times per day ask yourself: Am I being productive or just active? - Timothy Ferriss`,
      `If this is the only thing, I accomplish today will I be satisfied with my day? - Timothy Ferriss`,
      `Are you inventing things to do to avoid the important? - Timothy Ferriss`,
      `Get 1 percent better each day for one year you'll end up thirty-seven times better. - James Clear`,
      `Hearing your bad habits spoken aloud makes the consequences seem more real. - James Clear`,
      `If I miss one day a simple rule: never miss twice. Missing once is an accident. Missing twice is the start of a new habit. - James Clear`,
      `Consistency of effort over the long run is everything. - Angela Duckworth`,
      `True grit acknowledges the potential of failure, embraces the fear of disappointment, and rallies the team to reach and try, regardless of the potential of loss. - Jerry Colona`,
      `If motion doesn't lead to results why do we do it? We do it because motion allows us to feel like we're making progress without running the risk of failure. - James Clear`,
      `Most of us are experts at avoiding criticism. It doesn't feel good to fail or to be judged publicly so we tend to avoid situations where that might happen. - James Clear`,
      `Be proactive. Reactive people are driven by feelings by circumstances by conditions by their environment. Proactive people are driven by values—carefully thought about selected and internalized values. - Stephen R. Covey`,
      `Organize and execute around priorities. - Stephen R. Covey`,
      `You can't have the fruits without the roots. - Stephen R. Covey`,
      `An expert is a person who has made all the mistakes that can be made in a very narrow field. – Neils Bohr`,
      `Focus on being productive instead of busy. - Timothy Ferriss`,
      `What we fear doing most is usually what we most need to do. - Timothy Ferriss`,
      `It is equally important to measure the atrocious cost of inaction. - Timothy Ferriss`,
      `Being busy is most often used as a guise for avoiding the few critically important but uncomfortable actions. - Timothy Ferriss`,
      `Doing something unimportant well does not make it important. Requiring a lot of time does not make a task important. - Timothy Ferriss`,
      `Being busy is a form of laziness—lazy thinking and indiscriminate action. - Timothy Ferriss`,
      `It's not the writing part that's hard. What's hard is sitting down to write. - Steven Pressfield`,
      `Resistance comes when you do any act that rejects immediate gratification in favor of long-term growth health or integrity. - Steven Pressfield`,
      `Resistance arises from within. It is self-generated and self-perpetuated. - Steven Pressfield`,
      `We don't tell ourselves I'm never going to write my symphony. Instead we say I am going to write my symphony; I'm just going to start tomorrow. - Steven Pressfield`,
      `What does Resistance feel like? First unhappiness. We feel like hell. A low-grade misery pervades everything. We're bored we're restless. - Steven Pressfield`,
      `Resistance; I will not let it faze me; I will sit down and do my work. - Steven Pressfield`,
      `Inspiration strikes every morning at nine o'clock sharp. - Steven Pressfield`,
      `The most important thing about art is to work. Nothing else matters except sitting down every day and trying. - Steven Pressfield`,
      `Willpower is like muscle power: the more you exercise your will the stronger it gets. - William Irvine`,
      `Choices determine the difference between who you are and who you could be. - James Clear`,
      `You should be far more concerned with your current trajectory than with your current results. - James Clear`,
      `You get what you repeat. - James Clear`,
      `Fall in love with the process rather than the product. - James Clear`,
      `The ultimate purpose of habits is to solve the problems of life with as little energy and effort as possible. - James Clear`,
      `Does this behavior help me become the type of person I wish to be? - James Clear`,
      `To master a habit start with repetition not perfection. - James Clear`,
      `It's easy to train when you feel good but it's crucial to show up when you don't feel like it - even if you do less than you hope. - James Clear`,
      `Going to the gym for five minutes may not improve your performance but it reaffirms your identity. The all-or-nothing cycle of behavior change is just one pitfall that can derail your habits. - James Clear`,
      `Really successful people feel the same lack of motivation as everyone else. The difference is that they still find a way to show up despite the feelings of boredom. - James Clear`,
      `Professionals stick to the schedule; amateurs let life get in the way. Professionals know what is important to them and work toward it with purpose; amateurs get pulled off course by the urgencies of life. - James Clear`,
      `No excuses. If you aren't good at something work harder work smarter. - Darren Hardy`,
      `Have you ever been bitten by an elephant? How about a mosquito? It's the little things in life that will bite you. The decisions you think don't make any difference at all. It's the little things that inevitably and predictably derail your success. - Darren Hardy`,
      `Indulging in our bad habits doesn't seem to have any negative effects at all in the moment. - Darren Hardy`,
      `Top people have very clear goals. They know who they are, and they know what they want. They write it down and they make plans for its accomplishment. Unsuccessful people carry their goals around in their head like marbles rattling around in a can. - Darren Hardy`,
      `Don't wish it were easier; wish you were better. - Darren Hardy`,
      `Getting back on the treadmill the next day eager to try again is in my view even more reflective of grit. - Angela Duckworth`,
      `Enthusiasm is common. Endurance is rare. - Angela Duckworth`,
      `Grit grows as we figure out our life philosophy learn to dust ourselves off after rejection and disappointment and learn to tell the difference between low-level goals that should be abandoned quickly and higher-level goals that demand more tenacity. - Angela Duckworth`,
      `Failure always brings something valuable with it. I don't let it leave until I extract that value. - Scott Adams`,
      `It's easy to be passionate about things that are working out, but they drain your passion as they fail. - Scott Adams`,
      `A system is something you do on a regular basis that increases your odds of happiness in the long run. If you do something every day, it's a system. If you're waiting to achieve it someday in the future, it's a goal. - Scott Adams`,
      `If you want success, figure out the price, then pay it. It sounds trivial and obvious, but if you unpack the idea it has extraordinary power. - Scott Adams`,
      `The best way to get the attention and respect of exceptional people is to do exceptional work. Like attracts like. - James Clear`,
    ],
  },
  {
    category: 'mindful',
    index: 2,
    quotes: [
      `It never ceases to amaze me, you care about yourself more than other people, but care more about their opinions than your own" - Marcus Aurelius.`,
      `Ego is about who’s right. Truth is about what’s right. - Mike Maples Jr.`,
      `We would put our present selves’ wants above our future selves’ welfare. Why invest in a stranger’s future, especially at the expense of your own present comfort? - Kelly McGonigal`,
      `Refraining - breaking the habit of acting out impulsively - has something to do with giving up entertainment mentality. - Pema Chodron`,
      `Fear is a natural reaction to moving closer to the truth. - Pema Chodron`,
      `Mental toughness is persistence not intensity. - James Clear`,
      `Things become very clear when there is nowhere to escape. - Pema Chodron`,
      `Have unflappable coolness under pressure. - Ryan Holiday`,
      `Become more awake to who we are and what we’re doing rather than trying to improve or change or get rid of who we are or what we’re doing. - Pema Chodron`,
      `Life is such a miracle, and a lot of the time we feel only resentment about how it’s all working out for us. - Pema Chodron`,
      `Thinking that we can find some lasting pleasure and avoid pain is a hopeless cycle that goes round and round endlessly and causes us to suffer greatly. - Pema Chodron`,
      `Practice seeing yourself with a little distance. Get out of your own head. Detachment is a natural ego antidote. - Ryan Holiday`,
      `It is not “Who do I want to be in life?” but “What is it that I want to accomplish in life?” - Ryan Holiday`,
      `The sense of certainty that got you here can become a liability if you’re not careful. - Ryan Holiday`,
      `When you don’t know the actual facts about yourself, your consciousness pieces together a compelling story, much in the same way it does when you’re trying to read the minds of other people to make sense of why they act as they do. - Nicholas Epley`,
      `You must not think a man has lived long because he has white hair and wrinkles: he has not lived long, just existed long. - Seneca`,
      `But putting things off is the biggest waste of life: it snatches away each day as it comes and denies us the present by promising the future. - Seneca`,
      `The whole future lies in uncertainty: live immediately. - Seneca`,
      `Life is divided into three periods, past, present, and future. Of these, the present is short, the future is doubtful, the past is certain. - Seneca`,
      `Let no one rob me of a single day who is not going to make me an adequate return for such a loss. - Seneca`,
      `Mindfulness represents an alternative to living reactively. - Dan Harris`,
      `Meditation is like doing focused reps for your mind. Focus on the breath, lose your focus, bring it back to the breath, repeat. - Dan Harris`,
      `When you squelch something you give it power. Ignorance is not bliss. You should not run from your problems and pain. You should acknowledge them. - Dan Harris`,
      `The R.A.I.N. Technique for meditation: Recognize. Allow. Investigate. Non-identification. `,
      `Think carefully about how you spend your life because people often spend their lives chasing things that are neither as desirable nor as important as they seem. - Epictetus`,
      `Your brain is programmed to seek out the negative—dwindling resources, destructive weather, whatever's out to hurt you. - Darren Hardy`,
      `Keep your head while everyone else loses theirs. - Ryan Holiday`,
      `Resist impulse in favor of cold, hard common sense. - Ryan Holiday`,
      `That which blocks our path actually presents a new path. - Ryan Holiday`,
      `Behind mountains are more mountains. - Ryan Holiday`,
      `The key to feeling more whole and less shut off and shut down is to be able to see clearly who we are and what we're doing. - Pema Chodron`,
      `The desire to change is fundamentally a form of aggression toward yourself. - Pema Chodron`,
      `This simple act of staying still is part of what makes meditation willpower training effective. You're learning to not automatically follow every single impulse. - Kelly McGonigal`,
      `Train like an intelligent athlete, pushing our limits but also pacing ourselves. - Kelly McGonigal`,
      `We look into the future and fail to see the challenges of today. - Kelly McGonigal`,
      `We use all kinds of ways to escape. All addictions stem from the moment when we meet our edge and we just can't stand it. - Pema Chodron`,
      `Don't grab for entertainment the minute we feel a slight edge of boredom coming on. Practice not immediately filling up space just because there's a gap. - Pema Chodron`,
      `Acknowledge that right now we feel like a piece of shit. Explore the nature of that piece of shit. - Pema Chodron`,
      `Obsessively daydreaming of true romance: our minds just go wild trying to come up with companions to save us from despair. - Pema Chodron`,
      `Impermanence is meeting and parting. It's falling in love and falling out of love. Impermanence is bittersweet, like buying a new shirt and years later finding it as part of a patchwork quilt. - Pema Chodron`,
      `Emotional flexibility reflects the capacity to move freely and appropriately along a wide spectrum of emotions rather than responding rigidly or defensively. - Jim Loehr`,
      `Emotional resilience is the ability to bounce back from experiences of disappointment, frustration and even loss. - Jim Loehr`,
      `Shrug off all insults and slights. Also shrug off any praise. - William Irvine`,
      `The easiest way to gain happiness is to want the things you already have. - William Irvine `,
      `Do not over-love the things you enjoy. Be the user, but not the slave, of the gifts of fortune. - William Irvine `,
      `What upsets people are not things themselves but their judgments about these things. - William Irvine `,
      `Refuse to spend time engaging in "if only" thoughts about the past and present. - William Irvine `,
      `The story you tell yourself of your life is a confabulation. Don't mistake your constructed life story as the truth. - Derren Brown `,
      `Reconsider your judgements in a way that helps you. - Derren Brown `,
      `Remind yourself of the impermanence of things. Constantly remind ourselves of just how precious they are precisely because they may soon be gone. - Stoic`,
      `Reserve clause. Since the only thing truly under our control are our intentions and behaviors, the outcome of anything we try to do depends at the least in part on external circumstances. - Stoic`,
      `Some things are under my control and other things are not. - Handbook of Epictetus`,
      `People are upset not by things but by their judgements about things. - Handbook of Epictetus`,
      `What is beyond my control is indifferent to me. - Handbook of Epictetus`,
      `If you want any good, get it from within yourself. - Handbook of Epictetus`,
      `Now consider yourself and your significance within the universe. To say you are small in the cosmic scale of things is a gross overstatement. – Anderson Silver`,
      `There is neither fair nor unfair. You are owed nothing. Your life is an infinitesimally small part of the vast universe, so to think you are owed a favourable outcome because you deserve it is ignorant and egocentric. - Anderson Silver `,
      `There is no if. There only is, and you quite literally have no choice in the matter, so why bother to wish and hope of another nonexistent alternative universe where things would have been different? – Anderson Silver`,
      `Do not spoil what you have by desiring what you have not; remember that what you now have was once among the things you only hoped for. – Epicurus`,
      `It is not what happens to you, but how you react to it that matters. – Epictetus`,
      `No person has the power to have everything they want, but it is in their power not to want what they do not have, and to cheerfully put to good use what they do have - Seneca`,
      `Waste no more time arguing what a good man should be. Be One. - Marcus Aurelius`,
      `Do not explain your philosophy. Embody it. – Epictetus`,
      `Discipline of judgment: Things are as you see them, so make sure you see them rationally and objectively. Things do not affect you. Your judgment of things affects you. - Marcus Aurelius`,
      `People often act as though they can control the uncontrollable. - Daniel Gilbert`,
      `Become your own Socrates. Asking uncomfortable core questions. - Michael Starbird`,
      `Don't ruin a Tuesday wishing it was Friday. - Stoic`,
      `Contentedness comes from appreciating what we already have. - Stoic`,
      `We should periodically stop to reflect on the possibility that enjoyment (loved ones) will come to an end. By consciously thinking about the loss of what we have, we can regain our appreciation of it, and we can revitalize our capacity for joy. - Irvine`,
      `The Stoics enjoyed whatever good things happened to be available, but even as they did so, they prepared themselves to give up the things in question. - Irvine`,
      `We humans are unhappy in large part because we are insatiable; after working hard to get what we want; we routinely lose interest in the object of our desire. Rather than feeling satisfied, we feel a bit bored, and in response to this boredom, we go on to form new, even grander desires. - Irvine`,
      `One key to happiness is to forestall the [hedonic] adaptation process: We need to take steps to prevent ourselves from taking for granted, once we get them, the things we worked so hard to get. - Irvine`,
      `The easiest way for us to gain happiness is to learn how to want the things we already have. - Irvine`,
      `As we go about our day, we should periodically pause to reflect on the fact that we will not live forever and therefore that this day could be our last. - Irvine`,
      `After expressing his appreciation that his glass is half full rather than being completely empty, [a Stoic] will go on to express his delight in even having a glass: It could, after all, have been broken or stolen. - Stoic`,
      `Negative visualization is a powerful antidote to hedonic adaptation. By consciously thinking about the loss of what we have, we can regain our appreciation of it, and with this regained appreciation we can revitalize our capacity for joy. `,
      `There are things over which we have complete control, things over which we have no control at all, and things over which we have some but not complete control. - Stoic`,
      `By exposing ourselves to a small amount of a weakened virus now, we create in ourselves an immunity that will protect us from a debilitating illness in the future. - Irvine`,
      `When dealing with an annoying person, it also helps to keep in mind that our annoyance at what he does will almost invariably be more detrimental to us than whatever it is he is doing. - Irvine`,
      `It is foolish for us to worry about what other people think of us and particularly foolish for us to seek the approval of people whose values we reject. - Epictetus`,
      `Some things are in our power and some are not. Examples of things not in our power: reputation, power, and the things that are not our own acts. - Epictetus`,
      `Remember, if you think the things that are in the power of others are in your own power, then you will be hindered, frustrated, and annoyed. - Epictetus`,
      `Mindfulness represents an alternative to living reactively. -  Dan Harris`,
    ],
  },
  {
    category: 'misc',
    index: 3,
    quotes: [
      `Cognitive Dissonance: The Engine of Self-justification - Carol Tavris`,
      `Cognitive dissonance is a state of tension that occurs whenever a person holds two cognitions (ideas, attitudes, beliefs, opinions) that are psychologically inconsistent - Carol Tavris`,
      `The Pyramid of Choice. But by the time the person is at the bottom of the pyramid, ambivalence will have morphed into certainty, and they will be miles away from anyone who took a different route - Carol Tavris`,
      `Our mistake-phobic culture, or equating stupidity with mistakes, causes people not to learn from their mistakes. - Carol Tavris`,
      `Great rewards will accrue to those who can take conceptual knowledge from one problem or domain and apply it in an entirely new one - David Epstein`,
      `Hypercorrection effect: The more confident a learner is of their wrong answer, the better the information sticks when they subsequently learn the right answer. - David Epstein`,
      `Tolerating big mistakes can create the best learning opportunities. - David Epstein`,
      `Letting go of judgments(+/- values to events) does not mean ignoring errors. It simply means seeing events as they are and not adding anything to them - Timothy Gallwey`,
      `Our levels of desire, patience, persistence, and confidence end up playing a much larger role in success than sheer reasoning powers - Robert Greene`,
      `You must think of three essential steps in your apprenticeship: Deep Observation (the Passive Mode), Skills Acquisition (the Practice Mode) and Experimentation (the Active Mode) - Robert Greene`,
      `Real pleasure comes from overcoming challenges, feeling confidence in your abilities, gaining fluency in skills, and experiencing the power this brings. - Robert Greene`,
      `The Seven Deadly Realities: Rigidity, Accept the rigidity of others, but for yourself work to maintain your open spirit, get rid of bad habits, and continue to cultivate new ideas - Robert Greene`,
      `Complacency: after we develop some skills, we take things for granted.  Constantly remind yourself how little you truly know. - Robert Greene`,
      `Conservatism: if you gain attention or success for your work, this will naturally occur.  Make creativity rather than comfort your goal, and continue to be bold. - Robert Greene`,
      `So the goal isn’t to get good ideas; the goal is to get bad ideas. Because once you get enough bad ideas, then some good ones have to show up. - Seth Godin`,
      `If you’re looking for a formula for greatness, the closest we’ll ever get, I think, is this: Consistency driven by a deep love of the work - Maria Popova`,
      `In any situation in life, you only have three options. You always have three options.You can change it, you can accept it, or you can leave it. - Naval Ravikant`,
      `For too long, we have overemphasized the external aspect of choices (our options) and underemphasized our internal ability to choose (our actions) - Greg McKeown`,
      `Essential Intent is making one decision that will eliminate 1000 later decisions - Greg McKeown`,
      `The endowment effect: our tendency to undervalue things that aren’t ours and to overvalue things because we already own them. - Greg McKeown`,
      `There is no such thing as a neutral exchange. You leave someone either a little better or a little worse. - Dale Carnegie`,
      `If you think that the key to greater willpower is being harder on yourself, you are not alone. But you are wrong. It's self-compassion. - Kelly McGonigal`,
      `Self-compassion, being supportive and kind to yourself, especially with stress and failure, is associated with more motivation and better self-control.- Kelly McGonigal`,
      `Much of the horror of a breakup is the insult to our expectations of how this story was supposed to unfold versus how it actually did. - Katherine Thomas`,
      `Failure is just another way to learn how to do something right. - Marian Edelman`,
      `Love’s opposite is not hatred, it’s indifference. Hate is just as strong a bond as love and keeps us tied to our former love. - Katherine Thomas`,
      `Even after all this time, the sun never says to the earth “You owe me.” Look what happens with a love like that. It lights the whole sky. - Sufi Hafaz`,
      `Good endings, while never easy, are well worth the climb. - Katherine Thomas`,
      `The most common way people give up their power is by thinking they don’t have any. - Alice Walker`,
      `Forgiveness is not about anyone else at all. It’s about you—and your choice to not be defined by this painful experience moving forward. - Katherine Thomas`,
      `The way to make a mountain out of a mole hill is to add dirt. - Anonymous`,
      `You know it’s love when all you want is that person to be happy, even if you’re not part of their happiness. - Julia Roberts`,
      `Who can I meet who can positively influence me? Let their glow rub off on you. Befriend the person you think is the biggest, baddest, most successful person in your field. - Darren Hardy`,
      `It doesn't do any good to try to get rid of our so-called negative aspects, because in that process we also get rid of our basic wonderfulness. - Pema Chodron`,
      `It's part of being human to feel discomfort. We don't even have to call it suffering. - Pema Chodron`,
      `The warrior's journey is often extremely inconvenient. - Pema Chodron`,
      `Without desires we'd become depressed. - Kelly McGonigal`,
      `Things become very clear when there is nowhere to escape. - Pema Chodron`,
      `Thinking that we can find some lasting pleasure and avoid pain is a hopeless cycle that goes round and round endlessly and causes us to suffer greatly. - Pema Chodron`,
      `Blaming others is a very common, ancient, well-perfected device for trying to feel better. Blaming is a way to protect our hearts. - Pema Chodron`,
      `Disappointment, embarrassment, irritation, resentment, anger, jealousy, and fear, instead of being bad news, are actually very clear moments that teach us where it is that we're holding back. They teach us to perk up and lean in when we feel we'd rather collapse and back away. - Pema Chodron`,
      `Meet whatever arises with curiosity and don't make it such a big deal. - Pema Chodron`,
      `Mindfulness: It's a lifetime's journey to relate honestly to the immediacy of our experience and to respect ourselves enough not to judge it. - Pema Chodron`,
      `Honesty without kindness makes us feel grim. - Pema Chodron`,
      `We can endure a lot of pain and pleasure for the sake of finding out who we are and what this world is. - Pema Chodron`,
      `The person attempting to travel two roads at once will get nowhere. - Xun Zi`,
      `Living doesn't cost much but showing off does. - Jeffrey D. Sachs`,
      `The days are long, but the decades are short. - Sam Altman`,
      `The longer I live, the more I notice how valuable it is to do one simple thing: be kind. - James Clear`,
      `If you want to do a good deed, do it now. The time will pass, and you will not have the chance again. - Leo Tolstoy`,
      `Proactive people aren't pushy. They're smart, they're value driven, they read reality and they know what's needed. - Stephen R. Covey`,
      `Almost all of the world-class athletes and other peak performers are visualizers. They see it; they feel it; they experience it before they actually do it. They begin with the end in mind. - Stephen R. Covey`,
      `Integrity is fundamentally the value we place on ourselves. It's our ability to make and keep commitments to ourselves to walk our talk. It's honor with self a fundamental part of the Character Ethic the essence of proactive growth. - Stephen R. Covey`,
      `Integrity includes but goes beyond honesty. Honesty is telling the truth—in other words conforming our words to reality. Integrity is conforming reality to our words—in other words keeping promises and fulfilling expectations. - Stephen R. Covey`,
      `Flattery is counterfeit, and like counterfeit money, it will eventually get you into trouble if you pass it to someone else. - Dale Carnegie`,
      `Honest appreciation got results where criticism and ridicule failed. - Dale Carnegie`,
      `Find delight in your own resources and desire no joys greater than your inner joys. - William Irvine `,
      `You are living the dream you once had for yourself. - William Irvine `,
      `You are living in what to your ancestors would have been a dream world. You take for granted things that your ancestors had to live without. - William Irvine `,
      `There is a difference between contemplating something bad happening and worrying about it. Contemplation is an intellectual exercise. Conduct such exercises without affecting your emotions. - William Irvine `,
      `On the occasion of everything that causes you sadness, remember to use this 'dogma': not only is this not a misfortune, but it is a piece of good fortune for you to bear up under it courageously. - Marcus Aurelius`,
      `Love they neighbour: They were not objectively seeing the world as it is and were seeing it only through their eyes, and therefore did not even realize they were wronging you. – Anderson Silver`,
      `Don't be a snowflake, be a stoic. - Stoic`,
      `Pay attention to your enemies, for they are the first to discover your mistakes. —Antisthenes`,
      `Begin each day by telling yourself: Today I shall be meeting with interference, ingratitude, insolence, disloyalty, ill-will, and selfishness—all of them due to the offenders' ignorance of what is good or evil.— Marcus Aurelius`,
      `Management is doing things right; leadership is doing the right things. Management is efficiency in climbing the ladder of success; leadership determines whether the ladder is leaning against the right wall. - Stephen R. Covey`,
      `We are what we do. We are not what we think, or what we say, or how we feel. We are what we do. - Unknown`,
      `Happiness is health plus freedom. - Scott Adams`,
      `You can cure your loneliness only by doing the talking yourself and - most important - being heard. - Scott Adams`,
      `You're not in traffic, you are traffic. - Reddit`,
      `It is impossible to chart a course of change until you are able to look honestly at who you are today. - Jim Loehr`,
      `Get a life, a real life. Not a manic pursuit of the next promotion. - Anna Quindlen`,
      `Avoid survivorship bias. Don't just see success. See all the failures that led to the eventual success. - Tim Harford`,
      `Everything in life is based on your reference frame. Look at things in a new way and suddenly your problems fade away. - Rosamund Zander `,
      `Don't take yourself so damn seriously. - Rosamund Zander `,
      `When you squelch something you give it power. Ignorance is not bliss. You should not run from your problems and pain. You should acknowledge them. -  Dan Harris`,
      `Hedonic adaptation: the observed tendency of humans to quickly return to a relatively stable level of happiness despite major positive or negative events or life changes. -  Dan Harris`,
      `Wise selfish is when you show compassion and help others because it benefits you and makes you feel good. Compassion is in our own self-interest. -  Dan Harris`,
    ],
  },
  {
    category: 'journal',
    index: 4,
    quotes: [
      `How long will you put off what you are capable of doing just to continue what you are comfortable doing? - Jamse Clear`,
      `What future rewards do you put on sale each time you give in to temptation or procrastination? - Kelly McGonigal`,
      `Are you borrowing credit from tomorrow? Do you tell yourself you will make up for today’s behavior tomorrow—and if so, do you follow through? - Kelly McGonigal`,
      `What is the immediate payoff for giving in to temptation or procrastination? What is the long-term cost? Is this a fair trade? - Kelly McGonigal`,
      `What victimized story am I willing to let go of and what can I take responsibility for in how I co-created this situation? - Katherine Thomas`,
      `What is my anger demanding I change? What wants to wake up in me right now? - Katherine Thomas`,
      `What amends to myself or others can I now make to bring completion to this situation? - Katherine Thomas`,
      `If someone could only see my actions and not hear my words, what would they say are my priorities? - James Clear`,
      `What are you putting off out of fear? - Timothy Ferriss`,
      `Which 20% of sources are causing 80% of my problems and unhappiness? Which 20% of sources are resulting in 80% of my desired outcomes and happiness? - Timothy Ferriss`,
      `Fear setting: What is it costing you—financially emotionally and physically—to postpone action? `,
      `What are the core values that drive my life and work? - James Clear`,
      `How am I living and working with integrity right now? - James Clear`,
      `The question you should be asking isn't What do I want? or What are my goals? but What would excite me? - Timothy Ferriss`,
      `How should I spend my energy in a way that is consistent with my deepest values? - Jim Loehr`,
      `Do you know what your own dopamine triggers are? - Kelly McGonigal`,
      `What do you turn to when you're feeling stressed, anxious, or down? - Kelly McGonigal`,
      `How are you feeling? How are you really feeling? - Jerry Colona`,
      `What are you preventing yourself from feeling? - James Clear`,
      `What am I not saying that needs to be said? - Jerry Colona`,
      `What am I saying that's not being heard? - Jerry Colona`,
      `What's being said that I'm not hearing? - Jerry Colona`,
      `How have I complicit in creating the conditions in my life that I say I don't want? - Jerry Colona`,
      `When you worry, ask yourself, 'What am I choosing to not see right now?' - Ryan Holiday`,
      `What is something that you would like to do more of, or stop putting off, because you know that doing it will improve the quality of your life? - Kelly McGonigal`,
      `What is the most important long-term goal you'd like to focus your energy on? What immediate “want” is most likely to distract you or tempt you away from this goal? - Kelly McGonigal`,
      `Do you identify more with your impulses and desires, or with your long-term goals and values? - Kelly McGonigal`,
      `Do I have a problem right now? So much of our unhappiness comes from ruminating over past events or worrying about possible future ones. - Derren Brown`,
      `How might it be absolutely fine if things don't go as planned? - Derren Brown`,
      `If I was the last person in the world. Would I still want/ do X? `,
      `What do you want now? What do you want most? - Derek Sivers`,
      `Think of the ultimate outcome you are hoping to achieve. Is there a path to accomplishing this where you would encounter less resistance? - James Clear`,
      `Am I proud of what I am choosing to do? - James Clear`,
      `Whose expectations am I trying to fulfill? My own or those of someone else? - James Clear`,
      `Will this matter in six months? - James Clear`,
      `Am I tolerating my flaws or improving them? - James Clear`,
      `In what ways are you a difficult person to work with? What can you learn from that? - James clear`,
      `Over the last 10 years, what has become more important to you? What has become less important? - James Clear`,
      `What do you really wish you had the courage to do? - James Clear`,
      `Am I climbing the right mountain? - James Clear`,
      `What are you avoiding just because you know the answer is painful? - James Clear`,
      `What is the most neglected important area in my life right now? - James Clear`,
      `Am I happy with the trade offs I am making in my life right now? - James Clear`,
      `How would the person I wish to be act today? - James Clear`,
      `How are you contributing to your own struggle? - James Clear`,
      `Can my current habits carry me to my desired future? - James Clear`,
      `Time Paradox - Past: Who was I? x20, 3 significant events that have occurred in my life, what positive messages can be taken from these events? How can these lessons improve your future? `,
      `Time Paradox - Present: Who am I? X20, I am____ When I am I ___, Where am I ___, How do I feel_____`,
      `Time Paradox - Future: Who will I be? x15, I will be____. Concrete future goal: ____ Completed by: ____`,
    ],
  },
];

function quoteLength(categoryName) {
  return quoteLibrary.find((section) => section.category == categoryName).quotes.length - 1;
}

export const quoteIndexTracker = [
  { category: 'life', currentIndex: 0, categoryLength: quoteLength('life') },
  { category: 'habit', currentIndex: 0, categoryLength: quoteLength('habit') },
  {
    category: 'mindful',
    currentIndex: 0,
    categoryLength: quoteLength('mindful'),
  },
  { category: 'misc', currentIndex: 0, categoryLength: quoteLength('misc') },
  {
    category: 'journal',
    currentIndex: 0,
    categoryLength: quoteLength('journal'),
  },
];

export const miniQuoteArray = [
  `Optimize for tomorrow`,
  `Confort with discomfort`,
  `Surf the urge`,
  `Forgiveness when you fail`,
  `A tomorrow just like today`,
  `Kindness is contagious`,
  'Be 1 % better every day',
  'You get what you repeat',
  'Never miss twice',
  'You are not the exception',
  'Ego is the enemy',
  'Courage & Stoicism',
];
